# Get from https://github.com/Cysharp

name: Setup .NET SDKs
description: Setup .NET SDKs and environment variables
inputs:
  dotnet-version:
    description: .NET SDK versions to install
    required: false
    default: "7.0"
  dotnet-quality:
    description: "Optional quality of the build. The possible values are: daily, signed, validated, preview, ga."
    required: false
    default: "ga"

runs:
  using: "composite"
  steps:
    # see: https://github.com/actions/setup-dotnet
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}

    # see: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables
    - name: "Prepare Environment Variables (.NET SDK)"
      shell: bash
      run: |
        echo "MSBUILDDISABLENODEREUSE=1" | tee -a "$GITHUB_ENV"
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" | tee -a "$GITHUB_ENV"
        echo "DOTNET_NOLOGO=1" | tee -a "$GITHUB_ENV"
        echo "COMPlus_EnableDiagnostics=0" | tee -a "$GITHUB_ENV"
        echo "NUGET_XMLDOC_MODE=skip" | tee -a "$GITHUB_ENV"
        echo "DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION=1" | tee -a "$GITHUB_ENV"
        echo "TERM=xterm" | tee -a "$GITHUB_ENV"