name: Build-Test

on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: '7.0.x'
        working-directory: ./.github/actions/setup-dotnet
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test -c Debug --no-build
