name: Build-Test

on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: |
            7.0.x
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
